import { DM_Mono } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';

// Import the custom font directly in the global CSS

const dmMono = DM_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-mono',
  weight: '500',
});

export const metadata: Metadata = {
  title: 'Old Dhaka Coffee House',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`font-itcbenguiat ${dmMono.variable} 
        antialiased font-mono font-medium text-zinc-800`}
      >
        {children}
      </body>
    </html>
  );
}
