import {  DM_Mono, Lacquer } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";


const laquer = Lacquer({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lacquer",
  weight: "400",
})

const dmMono = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-mono",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Old Dhaka Coffee House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${laquer.variable} ${dmMono.variable} 
        antialiased font-mono font-medium text-zinc-800`}
      >
        {children}
      </body>
    </html>
  );
}
